# This rule is not used by the project nyallocator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the nyallocator.cybozu.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nyallocator
    app.kubernetes.io/managed-by: kustomize
  name: nodetemplate-editor-role
rules:
- apiGroups:
  - nyallocator.cybozu.io
  resources:
  - nodetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nyallocator.cybozu.io
  resources:
  - nodetemplates/status
  verbs:
  - get
