# This rule is not used by the project nyallocator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to nyallocator.cybozu.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nyallocator
    app.kubernetes.io/managed-by: kustomize
  name: nodetemplate-viewer-role
rules:
- apiGroups:
  - nyallocator.cybozu.io
  resources:
  - nodetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nyallocator.cybozu.io
  resources:
  - nodetemplates/status
  verbs:
  - get
