# This rule is not used by the project nyallocator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over nyallocator.cybozu.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nyallocator
    app.kubernetes.io/managed-by: kustomize
  name: nodetemplate-admin-role
rules:
- apiGroups:
  - nyallocator.cybozu.io
  resources:
  - nodetemplates
  verbs:
  - '*'
- apiGroups:
  - nyallocator.cybozu.io
  resources:
  - nodetemplates/status
  verbs:
  - get
