kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nyallocator-cluster
nodes:
  - role: control-plane
    labels:
      cke.cybozu.com/role: cs
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "node.cybozu.io/spare=true:NoSchedule"
  - role: control-plane
    labels:
      cke.cybozu.com/role: cs
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "node.cybozu.io/spare=true:NoSchedule"
  - role: control-plane
    labels:
      cke.cybozu.com/role: cs
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "node.cybozu.io/spare=true:NoSchedule"
  - role: worker
    labels:
      cke.cybozu.com/role: cs
      nyallocator.cybozu.io/node-template: cs
  - role: worker
    labels:
      cke.cybozu.com/role: cs
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "node.cybozu.io/spare=true:NoSchedule"
  - role: worker
    labels:
      cke.cybozu.com/role: cs
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "node.cybozu.io/spare=true:NoSchedule"
  - role: worker
    labels:
      cke.cybozu.com/role: ss
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "node.cybozu.io/spare=true:NoSchedule"
  - role: worker
    labels:
      cke.cybozu.com/role: ss
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "node.cybozu.io/spare=true:NoSchedule"
  - role: worker
    labels:
      cke.cybozu.com/role: ss
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "node.cybozu.io/spare=true:NoSchedule"
