apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: deny-edit-nyallocator-label
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["nodes"]
        operations: ["UPDATE"]
  validations:
    - expression: |
        request.userInfo.username == "system:serviceaccount:nyallocator-system:nyallocator-controller-manager" ||
        object.metadata.labels["nyallocator.cybozu.io/node-template"] == oldObject.metadata.labels["nyallocator.cybozu.io/node-template"]
      message: |
        Only the controller can change or remove the "nyallocator.cybozu.io/node-template" label on Node.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: deny-edit-nyallocator-label-binding
spec:
  policyName: deny-edit-nyallocator-label
  validationActions: ["Deny"]
  matchResources:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["nodes"]
        operations: ["UPDATE"]
